DROP TABLE MYCLASS;

CREATE TABLE MYCLASS
(
	MY_ID NUMERIC(9,0)  NOT NULL  ,
	MY_NAME CHARACTER VARYING(256)  , 
	MYDOCFILEDATA BYTEA  , 
	MYDOCFILENAME CHARACTER VARYING(256)  , 
	MYDOCTWOFILEDATA BYTEA  , 
	MYDOCTWOFILENAME CHARACTER VARYING(256) ,
	MyClassVer NUMERIC (4, 0)  NOT NULL ,
	dmLastUpdateDate	TIMESTAMP WITH TIME ZONE	NOT NULL ,
	PRIMARY KEY ( 
	MY_ID  )
);